return function(add)
    add("MetalDoorLvl1", "Basic Metal Door", "metal", 650, "MetalWelding", 350, 250, "MetalPlates", "MetalScrap", nil, "Metal_Light", "MetalDoor", "ZombieThumpMetal", "standard")
    add("MetalDoorLvl2", "Simple Metal Door", "metal", 750, "MetalWelding", 400, 275, "MetalPlates", nil, nil, "Metal_Light", "MetalDoor", "ZombieThumpMetal", "standard")
    add("WhiteMetalDoor", "White Metal Door", "metal", 800, "MetalWelding", 425, 275, "MetalPlates", "MetalBars", nil, "Metal_Solid", "MetalDoor", "ZombieThumpMetal", "standard")
    add("TanMetalDoor", "Tan Metal Door", "metal", 800, "MetalWelding", 425, 275, "MetalPlates", "MetalBars", nil, "Metal_Solid", "MetalDoor", "ZombieThumpMetal", "standard")
    add("BlackMetalDoorWithWindow", "Black Metal Door with Window", "metal_glazed", 700, "MetalWelding", 375, 225, "MetalPlates", "MetalBars", nil, "Metal_Solid", "MetalDoor", "ZombieThumpMetal", "standard")
    add("TanMetalDoorWithWindow", "Tan Metal Door with Window", "metal_glazed", 700, "MetalWelding", 375, 225, "MetalPlates", "MetalBars", nil, "Metal_Solid", "MetalDoor", "ZombieThumpMetal", "standard")
    add("BlackTwoPaneMetalDoor", "Black Two-Pane Metal Door", "metal_glazed", 650, "MetalWelding", 350, 225, "MetalPlates", "MetalBars", nil, "Metal_Solid", "MetalDoor", "ZombieThumpWindow", "standard")
    add("BlueServiceDoor", "Blue Service Door", "metal", 700, "MetalWelding", 375, 250, "MetalPlates", "Wood", "Screws", "Metal_Light", "MetalDoor", "ZombieThumpMetal", "standard")
    add("OrangeServiceDoor", "Orange Service Door", "metal", 700, "MetalWelding", 375, 250, "MetalPlates", "Wood", "Screws", "Metal_Light", "MetalDoor", "ZombieThumpMetal", "standard")
    add("LightRedServiceDoor", "Light Red Service Door", "metal", 700, "MetalWelding", 375, 250, "MetalPlates", "Wood", "Screws", "Metal_Light", "MetalDoor", "ZombieThumpMetal", "standard")
    add("BlackServiceDoor", "Black Service Door", "metal", 700, "MetalWelding", 375, 250, "MetalPlates", "Wood", "Screws", "Metal_Light", "MetalDoor", "ZombieThumpMetal", "standard")
    add("GreenServiceDoor", "Green Service Door", "metal", 700, "MetalWelding", 375, 250, "MetalPlates", "Wood", "Screws", "Metal_Light", "MetalDoor", "ZombieThumpMetal", "standard")
    add("RedServiceDoor", "Red Service Door", "metal", 700, "MetalWelding", 375, 250, "MetalPlates", "Wood", "Screws", "Metal_Light", "MetalDoor", "ZombieThumpMetal", "standard")
    add("WhiteServiceDoorWithPorthole", "White Service Door with Porthole", "metal_glazed", 650, "MetalWelding", 325, 225, "MetalPlates", "Wood", "Screws", "Metal_Light", "MetalDoor", "ZombieThumpMetal", "standard")
end
