return function(add)
    add("WoodenDoorLvl1", "Basic Wooden Door", "wood", 400, "Woodwork", 250, 150, "Wood", "Nails", nil, "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("RoughWoodenDoor", "Rough Wooden Door", "wood", 400, "Woodwork", 250, 150, "Wood", "Nails", nil, "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("WoodenDoorLvl2", "Sturdy Wooden Door", "wood", 500, "Woodwork", 300, 200, "Wood", "Nails", nil, "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("RusticWoodenDoor", "Rustic Wooden Door", "wood", 500, "Woodwork", 300, 200, "Wood", "Nails", nil, "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("WoodenDoorLvl3", "Artisan Wooden Door", "wood", 600, "Woodwork", 350, 250, "Wood", "Nails", nil, "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("OuthouseDoor", "Outhouse Door", "wood", 250, "Woodwork", 250, 0, "Wood", "Nails", nil, "Wood", "WoodDoor", "ZombieThumpWood", "standard")
    add("WhitePanelDoor", "White Panel Door", "wood", 625, "Woodwork", 450, 275, "Wood", "Nails", "Screws", "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("BrownPanelDoor", "Brown Panel Door", "wood", 625, "Woodwork", 450, 275, "Wood", "Nails", "Screws", "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("MahoganyPanelDoor", "Mahogany Panel Door", "wood", 625, "Woodwork", 450, 275, "Wood", "Nails", "Screws", "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("BluePanelDoor", "Blue Panel Door", "wood", 625, "Woodwork", 450, 275, "Wood", "Nails", "Screws", "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("WhiteDoorWithWindows", "White Door with Windows", "wood_glazed", 550, "Woodwork", 400, 250, "Wood", "Nails", "Screws", "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("BrownDoorWithWindows", "Brown Door with Windows", "wood_glazed", 550, "Woodwork", 400, 250, "Wood", "Nails", "Screws", "Wood_Solid", "WoodDoor", "ZombieThumpWood", "standard")
    add("BlueDoorWithWindow", "Blue Door with Window", "wood_glazed", 575, "Woodwork", 425, 250, "Wood", "Nails", "Screws", "Wood_Solid", "MetalDoor", "ZombieThumpWood", "standard")
    add("RedTwoPaneDoor", "Red Two-Pane Door", "wood_glazed", 500, "Woodwork", 350, 225, "Wood", "Nails", "Screws", "Wood_Solid", "MetalDoor", "ZombieThumpWindow", "standard")
    add("BlueTwoPaneDoor", "Blue Two-Pane Door", "wood_glazed", 500, "Woodwork", 350, 225, "Wood", "Nails", "Screws", "Wood_Solid", "MetalDoor", "ZombieThumpWindow", "standard")
    add("GreenStripedTwoPaneDoor", "Green-Striped Two-Pane Door", "wood_glazed", 500, "Woodwork", 350, 225, "Wood", "Nails", "Screws", "Wood_Solid", "MetalDoor", "ZombieThumpWindow", "standard")
    add("BrownTwoPaneDoor", "Brown Two-Pane Door", "wood_glazed", 500, "Woodwork", 350, 225, "Wood", "Nails", "Screws", "Wood_Solid", "MetalDoor", "ZombieThumpWindow", "standard")
    add("DarkBrownTwoPaneDoor", "Dark Brown Two-Pane Door", "wood_glazed", 500, "Woodwork", 350, 225, "Wood", "Nails", "Screws", "Wood_Solid", "MetalDoor", "ZombieThumpWindow", "standard")
    add("BlackFullGlassDoor", "Black Full-Glass Door", "wood_glazed", 425, "Woodwork", 300, 175, "Wood", "Nails", "Screws", "Glass_Solid", "MetalDoor", "ZombieThumpWindow", "standard")
    add("BrownFullGlassDoor", "Brown Full-Glass Door", "wood_glazed", 425, "Woodwork", 300, 175, "Wood", "Nails", "Screws", "Glass_Solid", "MetalDoor", "ZombieThumpWindow", "standard")
end
