require "LMION/Debug/Registry"

LMION.Debug.Showroom = LMION.Debug.Showroom or {}

local Profiles = LMION.Debug.Showroom.Profiles or {}
LMION.Debug.Showroom.Profiles = Profiles

Profiles.names = {
    ["carpentry_01_49"] = "Wood Door (Shoddy)",
    ["carpentry_01_53"] = "Wood Door (Poor)",
    ["carpentry_01_57"] = "Wood Door (Artisan)",
    ["fixtures_bathroom_01_49"] = "Small Blue Door",
    ["fixtures_bathroom_01_65"] = "Small Pink Door",
    ["fixtures_bathroom_02_17"] = "Blue Restroom Door",
    ["fixtures_bathroom_02_33"] = "Outhouse Door",
    ["fixtures_doors_01_1"] = "White Wooden Door",
    ["fixtures_doors_01_109"] = "Brown Sliding Glass Door",
    ["fixtures_doors_01_117"] = "White Sliding Glass Door",
    ["fixtures_doors_01_13"] = "Cherry Door",
    ["fixtures_doors_01_17"] = "Tan Door with Window",
    ["fixtures_doors_01_21"] = "Black Door with Window",
    ["fixtures_doors_01_25"] = "Blue Metal Door",
    ["fixtures_doors_01_29"] = "Rough Wooden Door",
    ["fixtures_doors_01_33"] = "Security Door",
    ["fixtures_doors_01_37"] = "Chestnut Glass Door",
    ["fixtures_doors_01_41"] = "Black Glass Door",
    ["fixtures_doors_01_45"] = "White Door with Windows",
    ["fixtures_doors_01_49"] = "Black 2 Pane Door",
    ["fixtures_doors_01_5"] = "Brown Door",
    ["fixtures_doors_01_53"] = "Metal Door Lvl2",
    ["fixtures_doors_01_57"] = "White Metal Door",
    ["fixtures_doors_01_61"] = "White Metal Door with Window",
    ["fixtures_doors_01_65"] = "Tan Metal Door",
    ["fixtures_doors_01_69"] = "Metal Door Lvl1",
    ["fixtures_doors_01_9"] = "Wooden Door",
    ["fixtures_doors_02_1"] = "Blue Door",
    ["fixtures_doors_02_13"] = "Black Metal Door",
    ["fixtures_doors_02_17"] = "Small Brown Panel Door",
    ["fixtures_doors_02_21"] = "Small White Panel Door",
    ["fixtures_doors_02_25"] = "Small Black Panel Door",
    ["fixtures_doors_02_41"] = "Double Black Glass Door - Left",
    ["fixtures_doors_02_45"] = "Double Black Glass Door - Right",
    ["fixtures_doors_02_49"] = "Double Grey Metal Door - Left",
    ["fixtures_doors_02_5"] = "Brown Door with Windows",
    ["fixtures_doors_02_53"] = "Double Grey Metal Door - Right",
    ["fixtures_doors_02_57"] = "Double Yellow Metal Door - Left",
    ["fixtures_doors_02_61"] = "Double Yellow Metal Door - Right",
    ["fixtures_doors_02_9"] = "Red Metal Door",
    ["fixtures_doors_fences_01_1"] = "Small Metal Fence Gate",
    ["fixtures_doors_fences_01_114"] = "Farm Double Gate",
    ["fixtures_doors_fences_01_129"] = "Big Wire Fence Gate",
    ["fixtures_doors_fences_01_13"] = "Tall Wooden Fence Gate",
    ["fixtures_doors_fences_01_17"] = "Small Wire Fence Gate",
    ["fixtures_doors_fences_01_21"] = "Tall Wrought Iron Gate",
    ["fixtures_doors_fences_01_25"] = "Big Pole Fence Gate",
    ["fixtures_doors_fences_01_29"] = "Small Pole Fence Gate",
    ["fixtures_doors_fences_01_34"] = "Double Wrought Iron Gate",
    ["fixtures_doors_fences_01_5"] = "Wood Fence Gate",
    ["fixtures_doors_fences_01_50"] = "Double Wooden Fence Gate",
    ["fixtures_doors_fences_01_66"] = "Big Double Wire Gate",
    ["fixtures_doors_fences_01_82"] = "Big Double Pole Gate",
    ["fixtures_doors_fences_01_9"] = "Small White Wooden Fence Gate",
    ["fixtures_doors_fences_01_98"] = "Double Door",
    ["industry_trucks_01_35"] = "Industrial Rolling Garage Door",
    ["location_community_church_small_01_25"] = "Blue Church Double Door - Left",
    ["location_community_church_small_01_29"] = "Blue Church Double Door - Right",
    ["location_community_church_small_01_65"] = "Brown Church Double Door - Left",
    ["location_community_church_small_01_69"] = "Brown Church Double Door - Right",
    ["location_community_police_01_5"] = "Jail Door",
    ["location_restaurant_pileocrepe_01_49"] = "Blue Panel Glass Door",
    ["location_restaurant_pileocrepe_01_53"] = "Orange Service Door",
    ["location_restaurant_pizzawhirled_01_57"] = "Brown Glass Door",
    ["location_restaurant_pizzawhirled_01_61"] = "Green Service Door",
    ["location_restaurant_seahorse_01_49"] = "Dark Brown Glass Door",
    ["location_restaurant_spiffos_01_49"] = "Brown Glass Door with Green Stripe",
    ["location_restaurant_spiffos_01_53"] = "Red Service Door",
    ["location_shop_fossoil_01_61"] = "Blue Glass Door",
    ["location_shop_gas2go_01_61"] = "Red Glass Door",
    ["walls_garage_01_19"] = "Green Garage Door",
    ["walls_garage_01_3"] = "White Garage Door",
    ["walls_garage_01_51"] = "Grey Garage Door",
    ["walls_garage_02_3"] = "Rolling Garage Door",
    ["walls_garage_02_35"] = "Red Window Garage Door",
    ["walls_garage_02_51"] = "Rolling Window Garage Door",
    ["walls_logs_41"] = "Log Door",
}

Profiles.special = {
    ["fixtures_bathroom_01_49"] = {
        kind = "small",
        frame = "standard",
        displayName = "Small Blue Door",
    },
    ["fixtures_bathroom_01_65"] = {
        kind = "small",
        frame = "standard",
        displayName = "Small Pink Door",
    },
    ["fixtures_doors_01_109"] = {
        kind = "sliding",
        frame = "none",
        displayName = "Brown Sliding Glass Door",
    },
    ["fixtures_doors_01_117"] = {
        kind = "sliding",
        frame = "none",
        displayName = "White Sliding Glass Door",
    },
    ["fixtures_doors_02_17"] = {
        kind = "small",
        frame = "standard",
        displayName = "Small Brown Panel Door",
    },
    ["fixtures_doors_02_21"] = {
        kind = "small",
        frame = "standard",
        displayName = "Small White Panel Door",
    },
    ["fixtures_doors_02_25"] = {
        kind = "small",
        frame = "standard",
        displayName = "Small Black Panel Door",
    },
    ["fixtures_doors_02_41"] = {
        kind = "paired",
        frame = "paired",
        side = "left",
        pair = "fixtures_doors_02_45",
        displayName = "Double Black Glass Door - Left",
    },
    ["fixtures_doors_02_45"] = {
        kind = "paired",
        frame = "paired",
        side = "right",
        pair = "fixtures_doors_02_41",
        displayName = "Double Black Glass Door - Right",
    },
    ["fixtures_doors_02_49"] = {
        kind = "paired",
        frame = "paired",
        side = "left",
        pair = "fixtures_doors_02_53",
        displayName = "Double Grey Metal Door - Left",
    },
    ["fixtures_doors_02_53"] = {
        kind = "paired",
        frame = "paired",
        side = "right",
        pair = "fixtures_doors_02_49",
        displayName = "Double Grey Metal Door - Right",
    },
    ["fixtures_doors_02_57"] = {
        kind = "paired",
        frame = "paired",
        side = "left",
        pair = "fixtures_doors_02_61",
        displayName = "Double Yellow Metal Door - Left",
    },
    ["fixtures_doors_02_61"] = {
        kind = "paired",
        frame = "paired",
        side = "right",
        pair = "fixtures_doors_02_57",
        displayName = "Double Yellow Metal Door - Right",
    },
    ["fixtures_doors_fences_01_1"] = {
        kind = "fence-low",
        frame = "none",
        displayName = "Small Metal Fence Gate",
    },
    ["fixtures_doors_fences_01_129"] = {
        kind = "fence-high",
        frame = "none",
        displayName = "Big Wire Fence Gate",
    },
    ["fixtures_doors_fences_01_13"] = {
        kind = "fence-high",
        frame = "none",
        displayName = "Tall Wooden Fence Gate",
    },
    ["fixtures_doors_fences_01_17"] = {
        kind = "fence-low",
        frame = "none",
        displayName = "Small Wire Fence Gate",
    },
    ["fixtures_doors_fences_01_21"] = {
        kind = "fence-high",
        frame = "none",
        displayName = "Tall Wrought Iron Gate",
    },
    ["fixtures_doors_fences_01_25"] = {
        kind = "fence-high",
        frame = "none",
        displayName = "Big Pole Fence Gate",
    },
    ["fixtures_doors_fences_01_29"] = {
        kind = "fence-low",
        frame = "none",
        displayName = "Small Pole Fence Gate",
    },
    ["fixtures_doors_fences_01_5"] = {
        kind = "fence-low",
        frame = "none",
        displayName = "Wood Fence Gate",
    },
    ["fixtures_doors_fences_01_9"] = {
        kind = "fence-low",
        frame = "none",
        displayName = "Small White Wooden Fence Gate",
    },
    ["location_community_church_small_01_25"] = {
        kind = "paired",
        frame = "paired",
        side = "left",
        pair = "location_community_church_small_01_29",
        displayName = "Blue Church Double Door - Left",
    },
    ["location_community_church_small_01_29"] = {
        kind = "paired",
        frame = "paired",
        side = "right",
        pair = "location_community_church_small_01_25",
        displayName = "Blue Church Double Door - Right",
    },
    ["location_community_church_small_01_65"] = {
        kind = "paired",
        frame = "paired",
        side = "left",
        pair = "location_community_church_small_01_69",
        displayName = "Brown Church Double Door - Left",
    },
    ["location_community_church_small_01_69"] = {
        kind = "paired",
        frame = "paired",
        side = "right",
        pair = "location_community_church_small_01_65",
        displayName = "Brown Church Double Door - Right",
    },
}

function Profiles.get(anchor)
    return Profiles.special[anchor]
end

function Profiles.getName(anchor)
    return Profiles.names[anchor]
end

return Profiles
